app_name: AetherPost
description: Terraform-style social media automation for developers
website_url: https://aether-post.com
author: AetherPost Team

ai:
  provider: openai
  api_key: YOUR_OPENAI_API_KEY_HERE
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 1000

features:
  auto_posting: true
  content_review: true
  analytics: true
  notifications: true
  ai_generation: true

defaults:
  posting_style: friendly
  auto_hashtags: true
  optimal_timing: true
  content_validation: true

notifications:
  enabled: true
  default_channels: []
  quiet_hours: {}